/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstractsystems.partita.metacode.grammar.node;

import com.abstractsystems.partita.metacode.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ADescriptortagnameBacktiksMctDescriptorChildren extends PMctDescriptorChildren
{
    private TColon _colon_;
    private PDescriptorLabelnameBacktiks _descriptorLabelnameBacktiks_;

    public ADescriptortagnameBacktiksMctDescriptorChildren()
    {
        // Constructor
    }

    public ADescriptortagnameBacktiksMctDescriptorChildren(
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PDescriptorLabelnameBacktiks _descriptorLabelnameBacktiks_)
    {
        // Constructor
        setColon(_colon_);

        setDescriptorLabelnameBacktiks(_descriptorLabelnameBacktiks_);

    }

    @Override
    public Object clone()
    {
        return new ADescriptortagnameBacktiksMctDescriptorChildren(
            cloneNode(this._colon_),
            cloneNode(this._descriptorLabelnameBacktiks_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADescriptortagnameBacktiksMctDescriptorChildren(this);
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PDescriptorLabelnameBacktiks getDescriptorLabelnameBacktiks()
    {
        return this._descriptorLabelnameBacktiks_;
    }

    public void setDescriptorLabelnameBacktiks(PDescriptorLabelnameBacktiks node)
    {
        if(this._descriptorLabelnameBacktiks_ != null)
        {
            this._descriptorLabelnameBacktiks_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._descriptorLabelnameBacktiks_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._colon_)
            + toString(this._descriptorLabelnameBacktiks_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._descriptorLabelnameBacktiks_ == child)
        {
            this._descriptorLabelnameBacktiks_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._descriptorLabelnameBacktiks_ == oldChild)
        {
            setDescriptorLabelnameBacktiks((PDescriptorLabelnameBacktiks) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
