/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstractsystems.partita.metacode.grammar.node;

import java.util.*;
import com.abstractsystems.partita.metacode.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMctAttribute extends PMctAttribute
{
    private PMctCodetagAttribname _mctCodetagAttribname_;
    private final LinkedList<PMctDescriptorChildren> _mctDescriptorChildren_ = new LinkedList<PMctDescriptorChildren>();

    public AMctAttribute()
    {
        // Constructor
    }

    public AMctAttribute(
        @SuppressWarnings("hiding") PMctCodetagAttribname _mctCodetagAttribname_,
        @SuppressWarnings("hiding") List<PMctDescriptorChildren> _mctDescriptorChildren_)
    {
        // Constructor
        setMctCodetagAttribname(_mctCodetagAttribname_);

        setMctDescriptorChildren(_mctDescriptorChildren_);

    }

    @Override
    public Object clone()
    {
        return new AMctAttribute(
            cloneNode(this._mctCodetagAttribname_),
            cloneList(this._mctDescriptorChildren_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMctAttribute(this);
    }

    public PMctCodetagAttribname getMctCodetagAttribname()
    {
        return this._mctCodetagAttribname_;
    }

    public void setMctCodetagAttribname(PMctCodetagAttribname node)
    {
        if(this._mctCodetagAttribname_ != null)
        {
            this._mctCodetagAttribname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mctCodetagAttribname_ = node;
    }

    public LinkedList<PMctDescriptorChildren> getMctDescriptorChildren()
    {
        return this._mctDescriptorChildren_;
    }

    public void setMctDescriptorChildren(List<PMctDescriptorChildren> list)
    {
        this._mctDescriptorChildren_.clear();
        this._mctDescriptorChildren_.addAll(list);
        for(PMctDescriptorChildren e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mctCodetagAttribname_)
            + toString(this._mctDescriptorChildren_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mctCodetagAttribname_ == child)
        {
            this._mctCodetagAttribname_ = null;
            return;
        }

        if(this._mctDescriptorChildren_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mctCodetagAttribname_ == oldChild)
        {
            setMctCodetagAttribname((PMctCodetagAttribname) newChild);
            return;
        }

        for(ListIterator<PMctDescriptorChildren> i = this._mctDescriptorChildren_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMctDescriptorChildren) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
