/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstractsystems.partita.metacode.grammar.node;

import java.util.*;
import com.abstractsystems.partita.metacode.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMctAttribtagPair extends PMctAttribtagPair
{
    private PMctCodetagOpen _mctCodetagOpen_;
    private final LinkedList<PMctCodechunkOptions> _mctCodechunkOptions_ = new LinkedList<PMctCodechunkOptions>();
    private PMctCodetagClose _mctCodetagClose_;

    public AMctAttribtagPair()
    {
        // Constructor
    }

    public AMctAttribtagPair(
        @SuppressWarnings("hiding") PMctCodetagOpen _mctCodetagOpen_,
        @SuppressWarnings("hiding") List<PMctCodechunkOptions> _mctCodechunkOptions_,
        @SuppressWarnings("hiding") PMctCodetagClose _mctCodetagClose_)
    {
        // Constructor
        setMctCodetagOpen(_mctCodetagOpen_);

        setMctCodechunkOptions(_mctCodechunkOptions_);

        setMctCodetagClose(_mctCodetagClose_);

    }

    @Override
    public Object clone()
    {
        return new AMctAttribtagPair(
            cloneNode(this._mctCodetagOpen_),
            cloneList(this._mctCodechunkOptions_),
            cloneNode(this._mctCodetagClose_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMctAttribtagPair(this);
    }

    public PMctCodetagOpen getMctCodetagOpen()
    {
        return this._mctCodetagOpen_;
    }

    public void setMctCodetagOpen(PMctCodetagOpen node)
    {
        if(this._mctCodetagOpen_ != null)
        {
            this._mctCodetagOpen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mctCodetagOpen_ = node;
    }

    public LinkedList<PMctCodechunkOptions> getMctCodechunkOptions()
    {
        return this._mctCodechunkOptions_;
    }

    public void setMctCodechunkOptions(List<PMctCodechunkOptions> list)
    {
        this._mctCodechunkOptions_.clear();
        this._mctCodechunkOptions_.addAll(list);
        for(PMctCodechunkOptions e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public PMctCodetagClose getMctCodetagClose()
    {
        return this._mctCodetagClose_;
    }

    public void setMctCodetagClose(PMctCodetagClose node)
    {
        if(this._mctCodetagClose_ != null)
        {
            this._mctCodetagClose_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mctCodetagClose_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mctCodetagOpen_)
            + toString(this._mctCodechunkOptions_)
            + toString(this._mctCodetagClose_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mctCodetagOpen_ == child)
        {
            this._mctCodetagOpen_ = null;
            return;
        }

        if(this._mctCodechunkOptions_.remove(child))
        {
            return;
        }

        if(this._mctCodetagClose_ == child)
        {
            this._mctCodetagClose_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mctCodetagOpen_ == oldChild)
        {
            setMctCodetagOpen((PMctCodetagOpen) newChild);
            return;
        }

        for(ListIterator<PMctCodechunkOptions> i = this._mctCodechunkOptions_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMctCodechunkOptions) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._mctCodetagClose_ == oldChild)
        {
            setMctCodetagClose((PMctCodetagClose) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
