/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstractsystems.partita.metacode.grammar.node;

public abstract class PMctCodetagOpen extends Node
{
    // Empty body
}
