/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.abstractsystems.partita.metacode.grammar.node;

import com.abstractsystems.partita.metacode.grammar.analysis.*;

@SuppressWarnings("nls")
public final class Start extends Node
{
    private PMctTranslationPass _pMctTranslationPass_;
    private EOF _eof_;

    public Start()
    {
        // Empty body
    }

    public Start(
        @SuppressWarnings("hiding") PMctTranslationPass _pMctTranslationPass_,
        @SuppressWarnings("hiding") EOF _eof_)
    {
        setPMctTranslationPass(_pMctTranslationPass_);
        setEOF(_eof_);
    }

    @Override
    public Object clone()
    {
        return new Start(
            cloneNode(this._pMctTranslationPass_),
            cloneNode(this._eof_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PMctTranslationPass getPMctTranslationPass()
    {
        return this._pMctTranslationPass_;
    }

    public void setPMctTranslationPass(PMctTranslationPass node)
    {
        if(this._pMctTranslationPass_ != null)
        {
            this._pMctTranslationPass_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pMctTranslationPass_ = node;
    }

    public EOF getEOF()
    {
        return this._eof_;
    }

    public void setEOF(EOF node)
    {
        if(this._eof_ != null)
        {
            this._eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eof_ = node;
    }

    @Override
    void removeChild(Node child)
    {
        if(this._pMctTranslationPass_ == child)
        {
            this._pMctTranslationPass_ = null;
            return;
        }

        if(this._eof_ == child)
        {
            this._eof_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(Node oldChild, Node newChild)
    {
        if(this._pMctTranslationPass_ == oldChild)
        {
            setPMctTranslationPass((PMctTranslationPass) newChild);
            return;
        }

        if(this._eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    public String toString()
    {
        return "" +
            toString(this._pMctTranslationPass_) +
            toString(this._eof_);
    }
}
