/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AManyActualTypeArgumentListUshrNoGt extends PActualTypeArgumentListUshrNoGt
{
    private PActualTypeArgumentList _actualTypeArgumentList_;
    private TComma _comma_;
    private PActualTypeArgumentUshrNoGt _actualTypeArgumentUshrNoGt_;

    public AManyActualTypeArgumentListUshrNoGt()
    {
        // Constructor
    }

    public AManyActualTypeArgumentListUshrNoGt(
        @SuppressWarnings("hiding") PActualTypeArgumentList _actualTypeArgumentList_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PActualTypeArgumentUshrNoGt _actualTypeArgumentUshrNoGt_)
    {
        // Constructor
        setActualTypeArgumentList(_actualTypeArgumentList_);

        setComma(_comma_);

        setActualTypeArgumentUshrNoGt(_actualTypeArgumentUshrNoGt_);

    }

    @Override
    public Object clone()
    {
        return new AManyActualTypeArgumentListUshrNoGt(
            cloneNode(this._actualTypeArgumentList_),
            cloneNode(this._comma_),
            cloneNode(this._actualTypeArgumentUshrNoGt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAManyActualTypeArgumentListUshrNoGt(this);
    }

    public PActualTypeArgumentList getActualTypeArgumentList()
    {
        return this._actualTypeArgumentList_;
    }

    public void setActualTypeArgumentList(PActualTypeArgumentList node)
    {
        if(this._actualTypeArgumentList_ != null)
        {
            this._actualTypeArgumentList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actualTypeArgumentList_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PActualTypeArgumentUshrNoGt getActualTypeArgumentUshrNoGt()
    {
        return this._actualTypeArgumentUshrNoGt_;
    }

    public void setActualTypeArgumentUshrNoGt(PActualTypeArgumentUshrNoGt node)
    {
        if(this._actualTypeArgumentUshrNoGt_ != null)
        {
            this._actualTypeArgumentUshrNoGt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actualTypeArgumentUshrNoGt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._actualTypeArgumentList_)
            + toString(this._comma_)
            + toString(this._actualTypeArgumentUshrNoGt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._actualTypeArgumentList_ == child)
        {
            this._actualTypeArgumentList_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._actualTypeArgumentUshrNoGt_ == child)
        {
            this._actualTypeArgumentUshrNoGt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._actualTypeArgumentList_ == oldChild)
        {
            setActualTypeArgumentList((PActualTypeArgumentList) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._actualTypeArgumentUshrNoGt_ == oldChild)
        {
            setActualTypeArgumentUshrNoGt((PActualTypeArgumentUshrNoGt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
