/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AManyExceptionTypeList extends PExceptionTypeList
{
    private PExceptionTypeList _exceptionTypeList_;
    private TComma _comma_;
    private PExceptionType _exceptionType_;

    public AManyExceptionTypeList()
    {
        // Constructor
    }

    public AManyExceptionTypeList(
        @SuppressWarnings("hiding") PExceptionTypeList _exceptionTypeList_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PExceptionType _exceptionType_)
    {
        // Constructor
        setExceptionTypeList(_exceptionTypeList_);

        setComma(_comma_);

        setExceptionType(_exceptionType_);

    }

    @Override
    public Object clone()
    {
        return new AManyExceptionTypeList(
            cloneNode(this._exceptionTypeList_),
            cloneNode(this._comma_),
            cloneNode(this._exceptionType_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAManyExceptionTypeList(this);
    }

    public PExceptionTypeList getExceptionTypeList()
    {
        return this._exceptionTypeList_;
    }

    public void setExceptionTypeList(PExceptionTypeList node)
    {
        if(this._exceptionTypeList_ != null)
        {
            this._exceptionTypeList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exceptionTypeList_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PExceptionType getExceptionType()
    {
        return this._exceptionType_;
    }

    public void setExceptionType(PExceptionType node)
    {
        if(this._exceptionType_ != null)
        {
            this._exceptionType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exceptionType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exceptionTypeList_)
            + toString(this._comma_)
            + toString(this._exceptionType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exceptionTypeList_ == child)
        {
            this._exceptionTypeList_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._exceptionType_ == child)
        {
            this._exceptionType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exceptionTypeList_ == oldChild)
        {
            setExceptionTypeList((PExceptionTypeList) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._exceptionType_ == oldChild)
        {
            setExceptionType((PExceptionType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
