/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AManyVariableDeclarators extends PVariableDeclarators
{
    private PVariableDeclarators _variableDeclarators_;
    private TComma _comma_;
    private PVariableDeclarator _variableDeclarator_;

    public AManyVariableDeclarators()
    {
        // Constructor
    }

    public AManyVariableDeclarators(
        @SuppressWarnings("hiding") PVariableDeclarators _variableDeclarators_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PVariableDeclarator _variableDeclarator_)
    {
        // Constructor
        setVariableDeclarators(_variableDeclarators_);

        setComma(_comma_);

        setVariableDeclarator(_variableDeclarator_);

    }

    @Override
    public Object clone()
    {
        return new AManyVariableDeclarators(
            cloneNode(this._variableDeclarators_),
            cloneNode(this._comma_),
            cloneNode(this._variableDeclarator_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAManyVariableDeclarators(this);
    }

    public PVariableDeclarators getVariableDeclarators()
    {
        return this._variableDeclarators_;
    }

    public void setVariableDeclarators(PVariableDeclarators node)
    {
        if(this._variableDeclarators_ != null)
        {
            this._variableDeclarators_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variableDeclarators_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PVariableDeclarator getVariableDeclarator()
    {
        return this._variableDeclarator_;
    }

    public void setVariableDeclarator(PVariableDeclarator node)
    {
        if(this._variableDeclarator_ != null)
        {
            this._variableDeclarator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variableDeclarator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variableDeclarators_)
            + toString(this._comma_)
            + toString(this._variableDeclarator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variableDeclarators_ == child)
        {
            this._variableDeclarators_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._variableDeclarator_ == child)
        {
            this._variableDeclarator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variableDeclarators_ == oldChild)
        {
            setVariableDeclarators((PVariableDeclarators) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._variableDeclarator_ == oldChild)
        {
            setVariableDeclarator((PVariableDeclarator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
