/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMinusAssignAssignmentOperator extends PAssignmentOperator
{
    private TMinusAssign _minusAssign_;

    public AMinusAssignAssignmentOperator()
    {
        // Constructor
    }

    public AMinusAssignAssignmentOperator(
        @SuppressWarnings("hiding") TMinusAssign _minusAssign_)
    {
        // Constructor
        setMinusAssign(_minusAssign_);

    }

    @Override
    public Object clone()
    {
        return new AMinusAssignAssignmentOperator(
            cloneNode(this._minusAssign_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusAssignAssignmentOperator(this);
    }

    public TMinusAssign getMinusAssign()
    {
        return this._minusAssign_;
    }

    public void setMinusAssign(TMinusAssign node)
    {
        if(this._minusAssign_ != null)
        {
            this._minusAssign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusAssign_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minusAssign_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minusAssign_ == child)
        {
            this._minusAssign_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minusAssign_ == oldChild)
        {
            setMinusAssign((TMinusAssign) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
