/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMjEqEqMpEqualityExpression extends PEqualityExpression
{
    private PEqualityExpression _equalityExpression_;
    private TEq _eq_;
    private PMpOutsideIncludedExprRelatedProdPlusId _mpOutsideIncludedExprRelatedProdPlusId_;

    public AMjEqEqMpEqualityExpression()
    {
        // Constructor
    }

    public AMjEqEqMpEqualityExpression(
        @SuppressWarnings("hiding") PEqualityExpression _equalityExpression_,
        @SuppressWarnings("hiding") TEq _eq_,
        @SuppressWarnings("hiding") PMpOutsideIncludedExprRelatedProdPlusId _mpOutsideIncludedExprRelatedProdPlusId_)
    {
        // Constructor
        setEqualityExpression(_equalityExpression_);

        setEq(_eq_);

        setMpOutsideIncludedExprRelatedProdPlusId(_mpOutsideIncludedExprRelatedProdPlusId_);

    }

    @Override
    public Object clone()
    {
        return new AMjEqEqMpEqualityExpression(
            cloneNode(this._equalityExpression_),
            cloneNode(this._eq_),
            cloneNode(this._mpOutsideIncludedExprRelatedProdPlusId_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMjEqEqMpEqualityExpression(this);
    }

    public PEqualityExpression getEqualityExpression()
    {
        return this._equalityExpression_;
    }

    public void setEqualityExpression(PEqualityExpression node)
    {
        if(this._equalityExpression_ != null)
        {
            this._equalityExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalityExpression_ = node;
    }

    public TEq getEq()
    {
        return this._eq_;
    }

    public void setEq(TEq node)
    {
        if(this._eq_ != null)
        {
            this._eq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eq_ = node;
    }

    public PMpOutsideIncludedExprRelatedProdPlusId getMpOutsideIncludedExprRelatedProdPlusId()
    {
        return this._mpOutsideIncludedExprRelatedProdPlusId_;
    }

    public void setMpOutsideIncludedExprRelatedProdPlusId(PMpOutsideIncludedExprRelatedProdPlusId node)
    {
        if(this._mpOutsideIncludedExprRelatedProdPlusId_ != null)
        {
            this._mpOutsideIncludedExprRelatedProdPlusId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mpOutsideIncludedExprRelatedProdPlusId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equalityExpression_)
            + toString(this._eq_)
            + toString(this._mpOutsideIncludedExprRelatedProdPlusId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equalityExpression_ == child)
        {
            this._equalityExpression_ = null;
            return;
        }

        if(this._eq_ == child)
        {
            this._eq_ = null;
            return;
        }

        if(this._mpOutsideIncludedExprRelatedProdPlusId_ == child)
        {
            this._mpOutsideIncludedExprRelatedProdPlusId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equalityExpression_ == oldChild)
        {
            setEqualityExpression((PEqualityExpression) newChild);
            return;
        }

        if(this._eq_ == oldChild)
        {
            setEq((TEq) newChild);
            return;
        }

        if(this._mpOutsideIncludedExprRelatedProdPlusId_ == oldChild)
        {
            setMpOutsideIncludedExprRelatedProdPlusId((PMpOutsideIncludedExprRelatedProdPlusId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
