/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import java.util.*;
import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMpAnnotationCall extends PAnnotationCall
{
    private PAnnotationNameOptions _annotationNameOptions_;
    private final LinkedList<PAnnotationCallParameterOptions> _annotationCallParameterOptions_ = new LinkedList<PAnnotationCallParameterOptions>();

    public AMpAnnotationCall()
    {
        // Constructor
    }

    public AMpAnnotationCall(
        @SuppressWarnings("hiding") PAnnotationNameOptions _annotationNameOptions_,
        @SuppressWarnings("hiding") List<PAnnotationCallParameterOptions> _annotationCallParameterOptions_)
    {
        // Constructor
        setAnnotationNameOptions(_annotationNameOptions_);

        setAnnotationCallParameterOptions(_annotationCallParameterOptions_);

    }

    @Override
    public Object clone()
    {
        return new AMpAnnotationCall(
            cloneNode(this._annotationNameOptions_),
            cloneList(this._annotationCallParameterOptions_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMpAnnotationCall(this);
    }

    public PAnnotationNameOptions getAnnotationNameOptions()
    {
        return this._annotationNameOptions_;
    }

    public void setAnnotationNameOptions(PAnnotationNameOptions node)
    {
        if(this._annotationNameOptions_ != null)
        {
            this._annotationNameOptions_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._annotationNameOptions_ = node;
    }

    public LinkedList<PAnnotationCallParameterOptions> getAnnotationCallParameterOptions()
    {
        return this._annotationCallParameterOptions_;
    }

    public void setAnnotationCallParameterOptions(List<PAnnotationCallParameterOptions> list)
    {
        this._annotationCallParameterOptions_.clear();
        this._annotationCallParameterOptions_.addAll(list);
        for(PAnnotationCallParameterOptions e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._annotationNameOptions_)
            + toString(this._annotationCallParameterOptions_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._annotationNameOptions_ == child)
        {
            this._annotationNameOptions_ = null;
            return;
        }

        if(this._annotationCallParameterOptions_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._annotationNameOptions_ == oldChild)
        {
            setAnnotationNameOptions((PAnnotationNameOptions) newChild);
            return;
        }

        for(ListIterator<PAnnotationCallParameterOptions> i = this._annotationCallParameterOptions_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAnnotationCallParameterOptions) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
