/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMpFilterWhere extends PFilterWhere
{
    private TMpWhereKeyword _mpWhereKeyword_;
    private PWhereExpression _whereExpression_;

    public AMpFilterWhere()
    {
        // Constructor
    }

    public AMpFilterWhere(
        @SuppressWarnings("hiding") TMpWhereKeyword _mpWhereKeyword_,
        @SuppressWarnings("hiding") PWhereExpression _whereExpression_)
    {
        // Constructor
        setMpWhereKeyword(_mpWhereKeyword_);

        setWhereExpression(_whereExpression_);

    }

    @Override
    public Object clone()
    {
        return new AMpFilterWhere(
            cloneNode(this._mpWhereKeyword_),
            cloneNode(this._whereExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMpFilterWhere(this);
    }

    public TMpWhereKeyword getMpWhereKeyword()
    {
        return this._mpWhereKeyword_;
    }

    public void setMpWhereKeyword(TMpWhereKeyword node)
    {
        if(this._mpWhereKeyword_ != null)
        {
            this._mpWhereKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mpWhereKeyword_ = node;
    }

    public PWhereExpression getWhereExpression()
    {
        return this._whereExpression_;
    }

    public void setWhereExpression(PWhereExpression node)
    {
        if(this._whereExpression_ != null)
        {
            this._whereExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whereExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mpWhereKeyword_)
            + toString(this._whereExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mpWhereKeyword_ == child)
        {
            this._mpWhereKeyword_ = null;
            return;
        }

        if(this._whereExpression_ == child)
        {
            this._whereExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mpWhereKeyword_ == oldChild)
        {
            setMpWhereKeyword((TMpWhereKeyword) newChild);
            return;
        }

        if(this._whereExpression_ == oldChild)
        {
            setWhereExpression((PWhereExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
