/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMpFieldsetParameterChildren extends PFieldsetParameterChildren
{
    private TComma _comma_;
    private PFieldname _fieldname_;
    private PParameterMappingToValue _parameterMappingToValue_;

    public AMpFieldsetParameterChildren()
    {
        // Constructor
    }

    public AMpFieldsetParameterChildren(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PFieldname _fieldname_,
        @SuppressWarnings("hiding") PParameterMappingToValue _parameterMappingToValue_)
    {
        // Constructor
        setComma(_comma_);

        setFieldname(_fieldname_);

        setParameterMappingToValue(_parameterMappingToValue_);

    }

    @Override
    public Object clone()
    {
        return new AMpFieldsetParameterChildren(
            cloneNode(this._comma_),
            cloneNode(this._fieldname_),
            cloneNode(this._parameterMappingToValue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMpFieldsetParameterChildren(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PFieldname getFieldname()
    {
        return this._fieldname_;
    }

    public void setFieldname(PFieldname node)
    {
        if(this._fieldname_ != null)
        {
            this._fieldname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fieldname_ = node;
    }

    public PParameterMappingToValue getParameterMappingToValue()
    {
        return this._parameterMappingToValue_;
    }

    public void setParameterMappingToValue(PParameterMappingToValue node)
    {
        if(this._parameterMappingToValue_ != null)
        {
            this._parameterMappingToValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parameterMappingToValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._fieldname_)
            + toString(this._parameterMappingToValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._fieldname_ == child)
        {
            this._fieldname_ = null;
            return;
        }

        if(this._parameterMappingToValue_ == child)
        {
            this._parameterMappingToValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._fieldname_ == oldChild)
        {
            setFieldname((PFieldname) newChild);
            return;
        }

        if(this._parameterMappingToValue_ == oldChild)
        {
            setParameterMappingToValue((PParameterMappingToValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
