/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMpSchemaNewDeclaration extends PSchemaNewDeclaration
{
    private PSchemaNew _schemaNew_;
    private PMatrixName _matrixName_;
    private PMatrixFieldAndBodyOptions _matrixFieldAndBodyOptions_;

    public AMpSchemaNewDeclaration()
    {
        // Constructor
    }

    public AMpSchemaNewDeclaration(
        @SuppressWarnings("hiding") PSchemaNew _schemaNew_,
        @SuppressWarnings("hiding") PMatrixName _matrixName_,
        @SuppressWarnings("hiding") PMatrixFieldAndBodyOptions _matrixFieldAndBodyOptions_)
    {
        // Constructor
        setSchemaNew(_schemaNew_);

        setMatrixName(_matrixName_);

        setMatrixFieldAndBodyOptions(_matrixFieldAndBodyOptions_);

    }

    @Override
    public Object clone()
    {
        return new AMpSchemaNewDeclaration(
            cloneNode(this._schemaNew_),
            cloneNode(this._matrixName_),
            cloneNode(this._matrixFieldAndBodyOptions_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMpSchemaNewDeclaration(this);
    }

    public PSchemaNew getSchemaNew()
    {
        return this._schemaNew_;
    }

    public void setSchemaNew(PSchemaNew node)
    {
        if(this._schemaNew_ != null)
        {
            this._schemaNew_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._schemaNew_ = node;
    }

    public PMatrixName getMatrixName()
    {
        return this._matrixName_;
    }

    public void setMatrixName(PMatrixName node)
    {
        if(this._matrixName_ != null)
        {
            this._matrixName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._matrixName_ = node;
    }

    public PMatrixFieldAndBodyOptions getMatrixFieldAndBodyOptions()
    {
        return this._matrixFieldAndBodyOptions_;
    }

    public void setMatrixFieldAndBodyOptions(PMatrixFieldAndBodyOptions node)
    {
        if(this._matrixFieldAndBodyOptions_ != null)
        {
            this._matrixFieldAndBodyOptions_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._matrixFieldAndBodyOptions_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._schemaNew_)
            + toString(this._matrixName_)
            + toString(this._matrixFieldAndBodyOptions_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._schemaNew_ == child)
        {
            this._schemaNew_ = null;
            return;
        }

        if(this._matrixName_ == child)
        {
            this._matrixName_ = null;
            return;
        }

        if(this._matrixFieldAndBodyOptions_ == child)
        {
            this._matrixFieldAndBodyOptions_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._schemaNew_ == oldChild)
        {
            setSchemaNew((PSchemaNew) newChild);
            return;
        }

        if(this._matrixName_ == oldChild)
        {
            setMatrixName((PMatrixName) newChild);
            return;
        }

        if(this._matrixFieldAndBodyOptions_ == oldChild)
        {
            setMatrixFieldAndBodyOptions((PMatrixFieldAndBodyOptions) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
