/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMpFilterFields extends PFilterFields
{
    private TMpFieldsKeyword _mpFieldsKeyword_;
    private PFilterFieldlist _filterFieldlist_;

    public AMpFilterFields()
    {
        // Constructor
    }

    public AMpFilterFields(
        @SuppressWarnings("hiding") TMpFieldsKeyword _mpFieldsKeyword_,
        @SuppressWarnings("hiding") PFilterFieldlist _filterFieldlist_)
    {
        // Constructor
        setMpFieldsKeyword(_mpFieldsKeyword_);

        setFilterFieldlist(_filterFieldlist_);

    }

    @Override
    public Object clone()
    {
        return new AMpFilterFields(
            cloneNode(this._mpFieldsKeyword_),
            cloneNode(this._filterFieldlist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMpFilterFields(this);
    }

    public TMpFieldsKeyword getMpFieldsKeyword()
    {
        return this._mpFieldsKeyword_;
    }

    public void setMpFieldsKeyword(TMpFieldsKeyword node)
    {
        if(this._mpFieldsKeyword_ != null)
        {
            this._mpFieldsKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mpFieldsKeyword_ = node;
    }

    public PFilterFieldlist getFilterFieldlist()
    {
        return this._filterFieldlist_;
    }

    public void setFilterFieldlist(PFilterFieldlist node)
    {
        if(this._filterFieldlist_ != null)
        {
            this._filterFieldlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._filterFieldlist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mpFieldsKeyword_)
            + toString(this._filterFieldlist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mpFieldsKeyword_ == child)
        {
            this._mpFieldsKeyword_ = null;
            return;
        }

        if(this._filterFieldlist_ == child)
        {
            this._filterFieldlist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mpFieldsKeyword_ == oldChild)
        {
            setMpFieldsKeyword((TMpFieldsKeyword) newChild);
            return;
        }

        if(this._filterFieldlist_ == oldChild)
        {
            setFilterFieldlist((PFilterFieldlist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
