/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMpLatestartSymbolCreation extends PLatestartSymbolCreation
{
    private TDot _dot_;
    private PSymbolCreation _symbolCreation_;

    public AMpLatestartSymbolCreation()
    {
        // Constructor
    }

    public AMpLatestartSymbolCreation(
        @SuppressWarnings("hiding") TDot _dot_,
        @SuppressWarnings("hiding") PSymbolCreation _symbolCreation_)
    {
        // Constructor
        setDot(_dot_);

        setSymbolCreation(_symbolCreation_);

    }

    @Override
    public Object clone()
    {
        return new AMpLatestartSymbolCreation(
            cloneNode(this._dot_),
            cloneNode(this._symbolCreation_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMpLatestartSymbolCreation(this);
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    public PSymbolCreation getSymbolCreation()
    {
        return this._symbolCreation_;
    }

    public void setSymbolCreation(PSymbolCreation node)
    {
        if(this._symbolCreation_ != null)
        {
            this._symbolCreation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._symbolCreation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dot_)
            + toString(this._symbolCreation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        if(this._symbolCreation_ == child)
        {
            this._symbolCreation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        if(this._symbolCreation_ == oldChild)
        {
            setSymbolCreation((PSymbolCreation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
