/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMpNewUsesSchema extends PNewUsesSchema
{
    private TDot _dot_;
    private TMpUsesKeyword _mpUsesKeyword_;
    private PNewSchemaOptions _newSchemaOptions_;

    public AMpNewUsesSchema()
    {
        // Constructor
    }

    public AMpNewUsesSchema(
        @SuppressWarnings("hiding") TDot _dot_,
        @SuppressWarnings("hiding") TMpUsesKeyword _mpUsesKeyword_,
        @SuppressWarnings("hiding") PNewSchemaOptions _newSchemaOptions_)
    {
        // Constructor
        setDot(_dot_);

        setMpUsesKeyword(_mpUsesKeyword_);

        setNewSchemaOptions(_newSchemaOptions_);

    }

    @Override
    public Object clone()
    {
        return new AMpNewUsesSchema(
            cloneNode(this._dot_),
            cloneNode(this._mpUsesKeyword_),
            cloneNode(this._newSchemaOptions_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMpNewUsesSchema(this);
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    public TMpUsesKeyword getMpUsesKeyword()
    {
        return this._mpUsesKeyword_;
    }

    public void setMpUsesKeyword(TMpUsesKeyword node)
    {
        if(this._mpUsesKeyword_ != null)
        {
            this._mpUsesKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mpUsesKeyword_ = node;
    }

    public PNewSchemaOptions getNewSchemaOptions()
    {
        return this._newSchemaOptions_;
    }

    public void setNewSchemaOptions(PNewSchemaOptions node)
    {
        if(this._newSchemaOptions_ != null)
        {
            this._newSchemaOptions_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newSchemaOptions_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dot_)
            + toString(this._mpUsesKeyword_)
            + toString(this._newSchemaOptions_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        if(this._mpUsesKeyword_ == child)
        {
            this._mpUsesKeyword_ = null;
            return;
        }

        if(this._newSchemaOptions_ == child)
        {
            this._newSchemaOptions_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        if(this._mpUsesKeyword_ == oldChild)
        {
            setMpUsesKeyword((TMpUsesKeyword) newChild);
            return;
        }

        if(this._newSchemaOptions_ == oldChild)
        {
            setNewSchemaOptions((PNewSchemaOptions) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
