/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import java.util.*;
import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMpSetItems extends PSetItems
{
    private PMatrixExpression _matrixExpression_;
    private final LinkedList<PSetItemsChildren> _setItemsChildren_ = new LinkedList<PSetItemsChildren>();

    public AMpSetItems()
    {
        // Constructor
    }

    public AMpSetItems(
        @SuppressWarnings("hiding") PMatrixExpression _matrixExpression_,
        @SuppressWarnings("hiding") List<PSetItemsChildren> _setItemsChildren_)
    {
        // Constructor
        setMatrixExpression(_matrixExpression_);

        setSetItemsChildren(_setItemsChildren_);

    }

    @Override
    public Object clone()
    {
        return new AMpSetItems(
            cloneNode(this._matrixExpression_),
            cloneList(this._setItemsChildren_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMpSetItems(this);
    }

    public PMatrixExpression getMatrixExpression()
    {
        return this._matrixExpression_;
    }

    public void setMatrixExpression(PMatrixExpression node)
    {
        if(this._matrixExpression_ != null)
        {
            this._matrixExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._matrixExpression_ = node;
    }

    public LinkedList<PSetItemsChildren> getSetItemsChildren()
    {
        return this._setItemsChildren_;
    }

    public void setSetItemsChildren(List<PSetItemsChildren> list)
    {
        this._setItemsChildren_.clear();
        this._setItemsChildren_.addAll(list);
        for(PSetItemsChildren e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._matrixExpression_)
            + toString(this._setItemsChildren_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._matrixExpression_ == child)
        {
            this._matrixExpression_ = null;
            return;
        }

        if(this._setItemsChildren_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._matrixExpression_ == oldChild)
        {
            setMatrixExpression((PMatrixExpression) newChild);
            return;
        }

        for(ListIterator<PSetItemsChildren> i = this._setItemsChildren_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PSetItemsChildren) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
