/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.unconventionalthinking.hierarchy.grammar.node;

import net.unconventionalthinking.hierarchy.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AMpSecondDynAccessor extends PSecondDynAccessor
{
    private TComma _comma_;
    private PSecondAccessor _secondAccessor_;

    public AMpSecondDynAccessor()
    {
        // Constructor
    }

    public AMpSecondDynAccessor(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PSecondAccessor _secondAccessor_)
    {
        // Constructor
        setComma(_comma_);

        setSecondAccessor(_secondAccessor_);

    }

    @Override
    public Object clone()
    {
        return new AMpSecondDynAccessor(
            cloneNode(this._comma_),
            cloneNode(this._secondAccessor_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMpSecondDynAccessor(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PSecondAccessor getSecondAccessor()
    {
        return this._secondAccessor_;
    }

    public void setSecondAccessor(PSecondAccessor node)
    {
        if(this._secondAccessor_ != null)
        {
            this._secondAccessor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._secondAccessor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._secondAccessor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._secondAccessor_ == child)
        {
            this._secondAccessor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._secondAccessor_ == oldChild)
        {
            setSecondAccessor((PSecondAccessor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
