/* Copyright 2012, 2013 Unconventional Thinking
 *
 * This file is part of Hierarchy.
 *
 * Hierarchy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * Hierarchy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Hierarchy.  
 * If not, see <http://www.gnu.org/licenses/>.
 */

package maintests.main;


import net.unconventionalthinking.lang.ExecutionInfo;
import net.unconventionalthinking.matrix.Matrix;
import net.unconventionalthinking.matrix.MatrixControl;
import net.unconventionalthinking.matrix.symbols.SymbolControl;
import net.unconventionalthinking.hierarchy.HierarchySettings;
import net.unconventionalthinking.hierarchy.persistence.PersistentMatricesManager_Server;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import static org.junit.Assert.*;




/**
 * This test seems to duplicate the test in the main project, the test generated by the "mainTests_Setup" class that
 * generates a sample matrix app that has a generated junit test that is run. But, I wasn't sure if this is working
 * like I thought it should, and wanted to maek sure we have a test that generates its java and class files to directories
 * that are NOT on the classpath. This test does that.
 *
 *
 * @author peterjoh
 */
public class MatrixLoadTest {


    static ExecutionInfo executeInfo;
    static MatrixControl matrixControl;
    static SymbolControl symbolControl;
    static HierarchySettings hierarchySettings;

    static PersistentMatricesManager_Server persistMatrix_Manager;

    static Matrix testMatrix_Persistant;




    public MatrixLoadTest() {    }


    @BeforeClass
    public static void setUpClass() throws Exception {

        persistMatrix_Manager = new PersistentMatricesManager_Server();
        hierarchySettings = persistMatrix_Manager.getHierarchySettings();
        
        persistMatrix_Manager.setMetaCompiler__HierarchyJar_Dir(HierarchySettings.test_HierarchyJar_Dir);
        persistMatrix_Manager.setMetaCompiler__javac_Dir(HierarchySettings.test_Javac_Dir);
        persistMatrix_Manager.setMetaCompiler__SrcMetaCode_BaseDir(MainTests_Constants.maintests_DirPath);
        persistMatrix_Manager.setMetaCompiler__AppClasses_PackageName(MainTests_Constants.maintests_generatedCode_PackageName);

        // output to a separate build_generatedmeta dir
        persistMatrix_Manager.setMetaCompiler__BuildMeta_BaseDir(MainTests_Constants.maintests_BuildMeta_DirPath);
        persistMatrix_Manager.setMetaCompiler__BuildFinal_BaseDir(MainTests_Constants.maintests_BuildFinal_DirPath);

        persistMatrix_Manager.set_PersistentMatrixName_Simple(PersistenceTestConstants.PersistentMatrixName_Simple);



        persistMatrix_Manager.metaCompile_PersistedMatrixCode();


        persistMatrix_Manager.load_PersistentMatrices();
 

    }

    @AfterClass
    public static void tearDownClass() throws Exception {
    }

    @Before
    public void setUp() {}
    @After
    public void tearDown() {}

    @Test
    public void loadTest() {
        assertNotNull(persistMatrix_Manager.getPersistMatrix());
    }
    
}